# Loading Data

In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

In [4]:
house_price_data = pd.read_csv("HousePricePrediction.csv")

In [18]:
# No need
house_price_data.drop(["Id"], axis=1, inplace=True)

In [23]:
house_price_data.isnull().sum()

MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [20]:
house_price_data["SalePrice"] = house_price_data["SalePrice"].fillna(house_price_data["SalePrice"].mean())

In [22]:
house_price_data= house_price_data.dropna()

In [24]:
house_price_data.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

# Data Preprocessing - Encoding

In [25]:
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
house_price_data = pd.get_dummies(house_price_data, columns=cols , drop_first=True)

# Splitting Data Using Train test split lib

In [27]:
from sklearn.model_selection import train_test_split

X = house_price_data.drop(["SalePrice"],axis=1)
y = house_price_data["SalePrice"]

X_train , X_test , y_train , y_test = train_test_split(
        X , y , test_size=0.2, random_state=0
)

In [28]:
X_train.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
1453,20,17217,5,2006,2006,0.0,1140.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2021,20,19508,5,1974,1974,0.0,1430.0,False,False,True,...,False,True,False,False,False,False,False,False,False,False
188,90,7018,5,1979,1979,0.0,1086.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1273,80,11512,7,1959,2006,0.0,1019.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1960,20,7560,5,1971,1971,613.0,864.0,False,False,True,...,False,False,False,True,False,False,False,False,False,False

# Train Linear Regresssion Model

In [30]:
from sklearn.linear_model import LinearRegression

house_price_pred_model = LinearRegression()
house_price_pred_model.fit(X_train,y_train)

LinearRegression()

# Evaluation of model

In [32]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

y_pred = house_price_pred_model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print(mean_absolute_percentage_error(y_test, y_pred))

R2 Score: 0.37414217961383156
MAE: 30829.93666432242
RMSE: 41138.558702301765
0.18742025463428386

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

house_price_pred_model = LinearRegression()
house_price_pred_model.fit(X_train_scaled, y_train)

y_pred = house_price_pred_model.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print(mean_absolute_percentage_error(y_test, y_pred))

R2 Score: 0.3741421796138532
MAE: 30829.93666432187
RMSE: 41138.55870230105
0.18742025463427797